site_name: Codecraft Blog
theme:
  name: null
  custom_dir: theme
repo_url: https://github.com/thomas-j-carter/thomas-j-carter.github.io
site_description: ""
site_author: "Thomas Carter"
copyright: "2026. All Rights Reserved. Thomas Carter"
nav:
  - 'index.md'
  - 'about.md'
  - 'bob.md'
extra_css:
  - 'css/extra.css'